// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    WithAuth: typeof import('./src/components/WithAuth.vue')['default']
  }
}

export { }
